"""First Migrations

Revision ID: a2a0060164e5
Revises: 
Create Date: 2025-05-03 19:15:24.610279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2a0060164e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_subject_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade_stream_branch_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('term', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_teacher_subject_assignments_grade_stream_branch_id', 'grade_stream_branch', ['grade_stream_branch_id'], ['id'])
        batch_op.drop_column('stream')
        batch_op.drop_column('grade')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_subject_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('stream', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('year')
        batch_op.drop_column('term')
        batch_op.drop_column('grade_stream_branch_id')

    # ### end Alembic commands ###
