"""added grade column

Revision ID: d1bf944e8a9c
Revises: a2a0060164e5
Create Date: 2025-05-03 20:18:36.771418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1bf944e8a9c'
down_revision = 'a2a0060164e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_subject_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('new_fk_column', 'grades', ['grade'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_subject_assignments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('grade')

    # ### end Alembic commands ###
